# codecov.yml
coverage:
  status:
    project:
      default:
        # Fails the PR check if total coverage is below 80%
        target: 80%
    patch:
      default:
        # Fails the check if new code in the PR does not have at least 80% coverage
        target: 80%