# codecov.yml
coverage:
  status:
    project:
      default:
        # Fails the PR check if the total coverage drops by more than 2%
        target: auto
        threshold: 2%
    patch:
      default:
        # Fails the check if the new code introduced in the PR (the "patch")
        # does not have at least 90% coverage.
        target: 90%