# codecov.yml
coverage:
  status:
    project:
      default:
        # Falla el check del PR si la cobertura total baja más de un 2%
        target: auto
        threshold: 2%
    patch:
      default:
        # Falla el check si el código nuevo introducido en el PR (el "patch")
        # no tiene al menos un 80% de cobertura.
        target: 80%