/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */
/* Runtime: no subprocess execution. Only (1) existsSync for .node under __dirname, (2) resolveLddPathWithoutShell + readFileSync of ldd for musl on Linux. See SECURITY.md in syntropylog. */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = resolveLddPathWithoutShell()
      if (!lddPath) return true // assume musl on unknown
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

/** Resolve path to ldd using PATH and fs.existsSync only (no subprocess). Reads process.env.PATH; documented in syntropylog SECURITY.md. */
function resolveLddPathWithoutShell() {
  const candidates = ['/usr/bin/ldd']
  const pathEnv = process.env.PATH
  if (pathEnv) {
    for (const dir of pathEnv.split(':')) {
      if (dir) candidates.push(join(dir.trim(), 'ldd'))
    }
  }
  for (const p of candidates) {
    try {
      if (existsSync(p)) return p
    } catch (_) {}
  }
  return null
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'syntropylog_native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.android-arm64.node')
          } else {
            nativeBinding = require('syntropylog-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'syntropylog_native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.android-arm-eabi.node')
          } else {
            nativeBinding = require('syntropylog-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'syntropylog_native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('syntropylog-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'syntropylog_native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('syntropylog-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'syntropylog_native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('syntropylog-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'syntropylog_native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./syntropylog_native.darwin-universal.node')
      } else {
        nativeBinding = require('syntropylog-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'syntropylog_native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.darwin-x64.node')
          } else {
            nativeBinding = require('syntropylog-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'syntropylog_native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.darwin-arm64.node')
          } else {
            nativeBinding = require('syntropylog-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'syntropylog_native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./syntropylog_native.freebsd-x64.node')
      } else {
        nativeBinding = require('syntropylog-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-x64-musl.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'syntropylog_native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./syntropylog_native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('syntropylog-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'syntropylog_native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./syntropylog_native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('syntropylog-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { configureNative, fastSerialize, fastSerializeFromJson, ping } = nativeBinding

module.exports.configureNative = configureNative
module.exports.fastSerialize = fastSerialize
module.exports.fastSerializeFromJson = fastSerializeFromJson
module.exports.ping = ping
