
services:
  redis:
    image: 'redis:7-alpine'
    container_name: beaconlog-redis-single
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local