version: '3.8'

services:
  nats-server:
    image: nats:2.9-alpine
    ports:
      - "4222:4222"

  api-gateway:
    image: node:18-alpine
    command: sh -c "node dist/examples/80-full-stack-nats/src/api-gateway/index.js"
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
    working_dir: /app
    depends_on:
      - nats-server

  sales-service:
    image: node:18-alpine
    command: sh -c "node dist/examples/80-full-stack-nats/src/sales-service/index.js"
    ports:
      - "3001:3001"
    volumes:
      - ../..:/app
    working_dir: /app
    depends_on:
      - nats-server

  dispatch-service:
    image: node:18-alpine
    command: sh -c "node dist/examples/80-full-stack-nats/src/dispatch-service/index.js"
    volumes:
      - ../..:/app
    working_dir: /app
    depends_on:
      - nats-server 