/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Inicializa o actualiza la configuración global del addon.
 * Se recomienda llamar esto una sola vez durante el init() en JS.
 */
export declare function configureNative(configJson: string): boolean
/**
 * Serialización completa en Rust: recibe los campos críticos directamente (Zero-Boundary cost)
 * y el objeto de metadatos para inspección profunda solo si es necesario.
 */
export declare function fastSerialize(level: string, message: string, timestamp: number, service: string, metadata: unknown): string
/** Validación Fase 0: compilación y enlace Node↔Rust. */
export declare function ping(): string
