/* tslint:disable */

/* auto-generated by NAPI-RS */

/**
 * Returns `true` when the config is VALID **and** native can serve THIS caller, `false`
 * otherwise. `false` cases (the JS caller MUST then fall back to the JS pipeline):
 *   1. unparseable JSON, or a masking rule / redact pattern whose regex we cannot compile
 *      — a rule we cannot honor must never silently let data through; and
 *   2. a *different* config is already installed in the process-global `OnceCell`. The
 *      native engine holds exactly one config; a second SyntropyLog instance
 *      (`createSyntropyLog`) whose masking rules differ CANNOT be served natively without
 *      masking its data with the first instance's rules — a cross-tenant PII leak. So we
 *      report `false` and let that instance mask correctly in JS.
 * An identical config (same rules, e.g. the singleton re-initialized, or two instances
 * configured the same) returns `true` — sharing the one global config is safe then.
 *
 * NOTE: this is the interim guard. The real fix is a per-instance native config (a napi
 * object owning its own `CompiledConfig`) so a divergent second instance keeps native too.
 */
export declare function configureNative(configJson: string): boolean;
export declare function fastSerialize(
  level: string,
  message: string,
  timestamp: number,
  service: string,
  metadata: unknown
): string;
/**
 * Same as fast_serialize but metadata is passed as a JSON string (one N-API crossing).
 * Use when JS can safely JSON.stringify(metadata) (no circular refs). On parse error returns error-prefix string.
 */
export declare function fastSerializeFromJson(
  level: string,
  message: string,
  timestamp: number,
  service: string,
  metadataJson: string
): string;
/** The two renderings of one log entry, produced from a single parse + truncate pass. */
export interface DualLine {
  /** The masked line — byte-identical to what `fastSerializeFromJson` returns. */
  masked: string;
  /**
   * The unmasked line, for transports declared exempt in `masking.exemptTransports`.
   * Same hygiene (ANSI strip, truncation, caps); no masking or redaction.
   */
  raw: string;
}
/**
 * Both renderings in ONE pass, for the case where the effective transport set contains
 * masked *and* exempt transports (an audit journal alongside console/APM).
 */
export declare function fastSerializeFromJsonDual(
  level: string,
  message: string,
  timestamp: number,
  service: string,
  metadataJson: string
): DualLine;
export declare function ping(): string;
