version: '3.8'

services:
  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    container_name: fluent-bit-collector
    ports:
      - "5170:5170/udp"
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf 