/**
 * FILE: src/index.ts
 * DESCRIPTION: The main entry point for the SyntropyLog framework.
 * It exports the singleton instance of the framework and key classes for users.
 */

// --- Main Framework Class ---
export { syntropyLog, SyntropyLog } from './SyntropyLog';

// --- Utility Classes for Advanced Configuration ---
export { SerializationManager } from './serialization/SerializationManager';
export { SanitizationEngine } from './sanitization/SanitizationEngine';

// --- Transport Classes for Custom Configuration ---
export { Transport } from './logger/transports/Transport';
export { ConsoleTransport } from './logger/transports/ConsoleTransport';
export { PrettyConsoleTransport } from './logger/transports/PrettyConsoleTransport';
export { CompactConsoleTransport } from './logger/transports/CompactConsoleTransport';
export { ClassicConsoleTransport } from './logger/transports/ClassicConsoleTransport';
export { ColorfulConsoleTransport } from './logger/transports/ColorfulConsoleTransport';
export { SpyTransport } from './logger/transports/SpyTransport';
export { AdapterTransport } from './logger/transports/AdapterTransport';

// --- Universal Logging Adapters (Agnostic Persistence) ---
export { UniversalAdapter } from './logger/adapters/UniversalAdapter';
export { UniversalLogFormatter } from './logger/formatters/UniversalLogFormatter';

// --- Default values (single source of truth; avoid magic numbers) ---
export { DEFAULT_VALUES } from './constants';
export type { DefaultValues } from './constants';

// --- Core Types for External Use ---
export type { LogLevel, LogEntry } from './types';

// --- Re-export types from separate type declaration file ---
// Types are exported via the .d.ts file generated by rollup-plugin-dts

// Export configuration types for better autocompletion
export type { SyntropyLogConfig } from './config';

// --- Universal Contracts for Advanced Users (Extensibility) ---
export type { ISerializer } from './serialization/types';
export { SerializationComplexity } from './serialization/types';
