/**
 * FILE: src/index.ts
 * DESCRIPTION: The main entry point for the SyntropyLog framework.
 * It exports the singleton instance of the framework and key classes for users.
 */

// --- Main Framework Class ---
export { syntropyLog, SyntropyLog } from './SyntropyLog';

// --- Utility Classes for Advanced Configuration ---
export { MaskingEngine } from './masking/MaskingEngine';
export { SanitizationEngine } from './sanitization/SanitizationEngine';

// --- Transport Classes for Custom Configuration ---
export { Transport } from './logger/transports/Transport';
export { ConsoleTransport } from './logger/transports/ConsoleTransport';
export { PrettyConsoleTransport } from './logger/transports/PrettyConsoleTransport';
export { CompactConsoleTransport } from './logger/transports/CompactConsoleTransport';
export { ClassicConsoleTransport } from './logger/transports/ClassicConsoleTransport';
export { SpyTransport } from './logger/transports/SpyTransport';

// --- Re-export types from separate type declaration file ---
// Types are exported via the .d.ts file generated by rollup-plugin-dts

// Export adapters (HTTP adapters are now in @syntropylog/adapters)
export * from './adapters/brokers';
export * from './adapters/serializers';

// Mock adapters for testing
export { MockBrokerAdapter } from './testing/MockBrokerAdapter';

export { MockHttpClient } from './testing/MockHttpClient';

export { MockSerializerRegistry } from './testing/MockSerializerRegistry';
